name: Create PDF
on: [push]
jobs:
  Create-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mkrakowitzer/actions-makepdfs@master
        with:
          markdown_dir: ''
          output_dir: out
      - uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: out
